from app.models.users import User
from app.models.airport import Airport
from app.models.flights import Flight
from app.models.seats import Seat
from app.models.booking import Booking
from app.models.payment import Payment
from app.models.recommendation_weights import RecommendationWeight
from app.models.search import Search
from app.models.recommendation_log import RecommendationLog
from app.models.saved_flights import SavedFlight