"""Initial schema

Revision ID: 8f512adc6e8a
Revises: 
Create Date: 2026-07-17 23:14:40.351622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f512adc6e8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.CheckConstraint('iata_code = UPPER(iata_code)', name='ck_airport_iata_uppercase'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=True)
    op.create_table('recommendation_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('cheapest', 'fastest', 'balanced', name='recommendation_mode'), nullable=False),
    sa.Column('price_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('duration_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('stops_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('duration_weight >= 0 AND duration_weight <= 1', name='ck_duration_weight_range'),
    sa.CheckConstraint('price_weight + duration_weight + stops_weight = 1.00', name='ck_weights_sum_to_one'),
    sa.CheckConstraint('price_weight >= 0 AND price_weight <= 1', name='ck_price_weight_range'),
    sa.CheckConstraint('stops_weight >= 0 AND stops_weight <= 1', name='ck_stops_weight_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mode')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default=sa.text("'user'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('origin_airport_id', sa.Integer(), nullable=False),
    sa.Column('destination_airport_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('aircraft_type', sa.String(length=100), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.CheckConstraint('arrival_time > departure_time', name='ck_arrival_after_departure'),
    sa.CheckConstraint('base_price > 0', name='ck_base_price_positive'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_duration_positive'),
    sa.CheckConstraint('origin_airport_id <> destination_airport_id', name='ck_origin_destination_different'),
    sa.CheckConstraint('stops >= 0', name='ck_stops_non_negative'),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number', 'departure_time', name='uq_flight_number_departure')
    )
    op.create_index('idx_flight_search', 'flights', ['origin_airport_id', 'destination_airport_id', 'departure_time'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin_airport_id', sa.Integer(), nullable=False),
    sa.Column('destination_airport_id', sa.Integer(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('travel_class', sa.Enum('economy', 'business', 'first', name='seat_class'), nullable=False),
    sa.Column('mode', sa.Enum('cheapest', 'fastest', 'balanced', name='recommendation_mode'), nullable=False),
    sa.Column('searched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('origin_airport_id <> destination_airport_id', name='ck_search_origin_destination_different'),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_route_date', 'searches', ['origin_airport_id', 'destination_airport_id', 'travel_date'], unique=False)
    op.create_index('ix_search_user_searched_at', 'searches', ['user_id', 'searched_at'], unique=False)
    op.create_index(op.f('ix_searches_user_id'), 'searches', ['user_id'], unique=False)
    op.create_table('recommendation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('computed_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('price_component', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('duration_component', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('stops_component', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('computed_score >= 0', name='ck_computed_score_non_negative'),
    sa.CheckConstraint('duration_component >= 0', name='ck_duration_component_non_negative'),
    sa.CheckConstraint('price_component >= 0', name='ck_price_component_non_negative'),
    sa.CheckConstraint('rank_position > 0', name='ck_rank_position_positive'),
    sa.CheckConstraint('stops_component >= 0', name='ck_stops_component_non_negative'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'flight_id', name='uq_search_flight'),
    sa.UniqueConstraint('search_id', 'rank_position', name='uq_search_rank')
    )
    op.create_index('ix_recommendation_search_rank', 'recommendation_logs', ['search_id', 'rank_position'], unique=False)
    op.create_table('saved_flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'flight_id', name='uq_user_saved_flight')
    )
    op.create_index('ix_saved_flight_user', 'saved_flights', ['user_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=5), nullable=False),
    sa.Column('seat_class', sa.Enum('economy', 'business', 'first', name='seat_class'), server_default=sa.text("'economy'"), nullable=False),
    sa.Column('price_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.CheckConstraint('price_multiplier > 0', name='ck_price_multiplier_positive'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'seat_number', name='uq_flight_seat')
    )
    op.create_index(op.f('ix_seats_flight_id'), 'seats', ['flight_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pnr', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'expired', name='booking_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('booked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_price >= 0', name='ck_booking_total_price_non_negative'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_flight', 'bookings', ['flight_id'], unique=False)
    op.create_index('ix_booking_seat', 'bookings', ['seat_id'], unique=False)
    op.create_index('ix_booking_user_booked_at', 'bookings', ['user_id', 'booked_at'], unique=False)
    op.create_index(op.f('ix_bookings_pnr'), 'bookings', ['pnr'], unique=True)
    op.create_index('ux_booking_confirmed_seat', 'bookings', ['seat_id'], unique=True, postgresql_where=sa.text("status = 'confirmed'"))
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('upi', 'credit_card', 'debit_card', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'refunded', name='payment_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index('ix_payment_status', 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ux_booking_confirmed_seat', table_name='bookings', postgresql_where=sa.text("status = 'confirmed'"))
    op.drop_index(op.f('ix_bookings_pnr'), table_name='bookings')
    op.drop_index('ix_booking_user_booked_at', table_name='bookings')
    op.drop_index('ix_booking_seat', table_name='bookings')
    op.drop_index('ix_booking_flight', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_seats_flight_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index('ix_saved_flight_user', table_name='saved_flights')
    op.drop_table('saved_flights')
    op.drop_index('ix_recommendation_search_rank', table_name='recommendation_logs')
    op.drop_table('recommendation_logs')
    op.drop_index(op.f('ix_searches_user_id'), table_name='searches')
    op.drop_index('ix_search_user_searched_at', table_name='searches')
    op.drop_index('ix_search_route_date', table_name='searches')
    op.drop_table('searches')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index('idx_flight_search', table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('recommendation_weights')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
