"""update seat model

Revision ID: b904c83867a0
Revises: 8f512adc6e8a
Create Date: 2026-07-21 00:37:55.203565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b904c83867a0'
down_revision: Union[str, Sequence[str], None] = '8f512adc6e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seats_flight_id'), table_name='seats')
    op.create_index('idx_flight_seat_class', 'seats', ['flight_id', 'seat_class'], unique=False)
    op.drop_constraint(op.f('seats_flight_id_fkey'), 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'flights', ['flight_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.create_foreign_key(op.f('seats_flight_id_fkey'), 'seats', 'flights', ['flight_id'], ['id'])
    op.drop_index('idx_flight_seat_class', table_name='seats')
    op.create_index(op.f('ix_seats_flight_id'), 'seats', ['flight_id'], unique=False)
    # ### end Alembic commands ###
